uploads = []

[[generated]]
id = "U-pEl03qiR00-kojtnquW"
uri = "file://artifacts/pitch-deck/public/hero.png"
type = "image"
title = "community impact hero"

[[generated]]
id = "I8fCDu2NwbTkt1rCjV0X3"
uri = "file://artifacts/pitch-deck/public/hands.png"
type = "image"
title = "hands seedling"

[[generated]]
id = "8YhBz9ejYxs62sT82H-JE"
uri = "file://artifacts/pitch-deck/public/community.png"
type = "image"
title = "community cafe"

[[outputs]]
id = "-c4lkqNDuCuZSV6KWeRB7"
uri = "file://My Impact - Full Feature List.docx"
type = "word_document"
title = "My Impact — Full Feature List (updated)"

[[outputs]]
id = "3CGeEUGYYhBHhLiUrA0Fe"
uri = "file://artifacts/api-server/backups/myimpact-db-backup-2026-05-02T0803.sql.tar.gz"
type = "unspecified"
title = "My Impact DB backup — 2026-05-02 08:03 UTC (gzipped SQL)"

[[outputs]]
id = "msVOrUykFWOjg_V5C1yGH"
uri = "file://myimpact-db-backup-2026-05-02T0803.sql.tar.gz"
type = "unspecified"
title = "My Impact DB backup — 2026-05-02 08:03 UTC (gzipped SQL)"

[[outputs]]
id = "9DIlfovuksPqXsDFNL3us"
uri = "file://myimpact-db-backup-2026-05-02T0808.sql.tar.gz"
type = "unspecified"
title = "My Impact DB backup — 2026-05-02 08:08 UTC (gzipped SQL)"

[[outputs]]
id = "ieFK-CsJyp7pavoPyHQQV"
uri = "file://myimpact-db-backup-2026-05-02T0814.sql.gz"
type = "unspecified"
title = "My Impact DB backup — 2026-05-02 08:14 UTC (gzipped SQL)"
