export interface Activity {
  id: string;
  name: string;
  shortName: string;
  category: string;
  proxy: string;
  proxyYear: string;
  unit: string;
  unitLabel: string;
  friendlyQuestion: string;
  defaultQuantity: number;
  valuePerUnit: number;
  sdg: string;
  sdgColor: string;
  description: string;
}

export const ACTIVITIES: Activity[] = [
  {
    id: "recycling",
    name: "Reducing household waste through recycling",
    shortName: "Recycling at home",
    category: "Environment",
    proxy: "Standard UK landfill tax avoided per recycling bin collected (GOV.UK, 2025) — £126.15/tonne × 0.01 tonnes per bin",
    proxyYear: "2025",
    unit: "bin",
    unitLabel: "Bins recycled per year",
    friendlyQuestion: "How many full recycling bins do you put out per year?",
    defaultQuantity: 26,
    valuePerUnit: 1.26,
    sdg: "Responsible Consumption and Production",
    sdgColor: "#BF8B2E",
    description: "Recycling paper, plastic, glass and other materials at home to reduce landfill.",
  },
  {
    id: "food_waste",
    name: "Reducing food waste at home",
    shortName: "Cutting food waste",
    category: "Environment",
    proxy: "Household savings from avoidable food waste (2015)",
    proxyYear: "2015",
    unit: "household",
    unitLabel: "Households",
    friendlyQuestion: "This counts for your household — just confirm you do this.",
    defaultQuantity: 1,
    valuePerUnit: 631.0,
    sdg: "Responsible Consumption and Production",
    sdgColor: "#BF8B2E",
    description: "Meal planning, composting, and using leftovers to cut food waste.",
  },
  {
    id: "eco_transport",
    name: "Using sustainable transport (cycling/walking)",
    shortName: "Cycling or walking",
    category: "Environment",
    proxy: "Value per mile cycled rather than driven (2019)",
    proxyYear: "2019",
    unit: "mile_per_year",
    unitLabel: "miles",
    friendlyQuestion: "Roughly how many miles do you travel by foot or bike each year instead of driving?",
    defaultQuantity: 310,
    valuePerUnit: 0.09,
    sdg: "Sustainable Cities and Communities",
    sdgColor: "#F99D26",
    description: "Walking or cycling instead of driving or using public transport.",
  },
  {
    id: "tree_planting",
    name: "Tree planting and green space projects",
    shortName: "Planting trees",
    category: "Environment",
    proxy: "Average cumulative benefit over 50 years per tree planted (2018)",
    proxyYear: "2018",
    unit: "tree",
    unitLabel: "trees",
    friendlyQuestion: "How many trees have you helped plant this year?",
    defaultQuantity: 5,
    valuePerUnit: 1195.0,
    sdg: "Life on Land",
    sdgColor: "#56C02B",
    description: "Planting trees or maintaining green spaces in your local community.",
  },
  {
    id: "charity_books",
    name: "Donating books and clothes to charity shops",
    shortName: "Donating to charity shops",
    category: "Community",
    proxy: "Average resale value of donated clothing items (2023)",
    proxyYear: "2023",
    unit: "bag",
    unitLabel: "bags",
    friendlyQuestion: "How many bags of books or clothes have you donated this year?",
    defaultQuantity: 4,
    valuePerUnit: 36.0,
    sdg: "Sustainable Cities and Communities",
    sdgColor: "#F99D26",
    description: "Donating reusable items to charity shops to support reuse and raise funds.",
  },
  {
    id: "food_bank",
    name: "Volunteering at a food bank",
    shortName: "Food bank volunteering",
    category: "Community",
    proxy: "Value of being supported by a food bank (2018)",
    proxyYear: "2018",
    unit: "session",
    unitLabel: "sessions",
    friendlyQuestion: "How many sessions do you volunteer at a food bank each year?",
    defaultQuantity: 12,
    valuePerUnit: 185.0,
    sdg: "Zero Hunger",
    sdgColor: "#DDA63A",
    description: "Sorting, packing and distributing food parcels to people in need.",
  },
  {
    id: "veterans_breakfast",
    name: "Volunteering at community social clubs",
    shortName: "Community social clubs",
    category: "Community",
    proxy: "Impact of loneliness on well-being",
    proxyYear: "",
    unit: "person",
    unitLabel: "people",
    friendlyQuestion: "How many people do you help through community social club volunteering each year?",
    defaultQuantity: 5,
    valuePerUnit: 109.0,
    sdg: "Good Health and Well-Being",
    sdgColor: "#4C9F38",
    description: "Volunteering at community social clubs, breakfast clubs, or companionship groups to reduce isolation.",
  },
  {
    id: "youth_mentoring",
    name: "Mentoring young people",
    shortName: "Mentoring young people",
    category: "Education",
    proxy: "Improved self-esteem in mentoring",
    proxyYear: "",
    unit: "young_person",
    unitLabel: "young people",
    friendlyQuestion: "How many young people do you mentor?",
    defaultQuantity: 2,
    valuePerUnit: 1240.0,
    sdg: "Quality Education",
    sdgColor: "#C5192D",
    description: "Providing guidance and support to young people to help them reach their potential.",
  },
  {
    id: "tutoring",
    name: "Tutoring or teaching skills",
    shortName: "Tutoring or teaching",
    category: "Education",
    proxy: "Adult learning course that made someone more satisfied with their life overall (2012)",
    proxyYear: "2012",
    unit: "person",
    unitLabel: "people",
    friendlyQuestion: "How many people do you tutor or teach?",
    defaultQuantity: 3,
    valuePerUnit: 231.0,
    sdg: "Quality Education",
    sdgColor: "#C5192D",
    description: "Helping others learn new skills through informal tutoring or coaching.",
  },
  {
    id: "fundraising",
    name: "Fundraising for charities",
    shortName: "Fundraising",
    category: "Community",
    proxy: "Improved reputation of organisation/charity (2016)",
    proxyYear: "2016",
    unit: "event",
    unitLabel: "events",
    friendlyQuestion: "How many fundraising events have you organised or taken part in?",
    defaultQuantity: 2,
    valuePerUnit: 185.0,
    sdg: "Reduced Inequalities",
    sdgColor: "#DD1367",
    description: "Organising or taking part in sponsored events, charity runs, or other fundraising.",
  },
  {
    id: "community_garden",
    name: "Community garden or allotment volunteering",
    shortName: "Community gardening",
    category: "Environment",
    proxy: "Ref 4.13 – Voluntary time for green infrastructure/biodiversity/green-space upkeep",
    proxyYear: "",
    unit: "hour",
    unitLabel: "hours",
    friendlyQuestion: "How many hours do you spend on community gardening or allotment work each year?",
    defaultQuantity: 50,
    valuePerUnit: 14.43,
    sdg: "Life on Land",
    sdgColor: "#56C02B",
    description: "Tending community gardens or allotments to produce food and create green spaces.",
  },
  {
    id: "blood_donation",
    name: "Donating blood",
    shortName: "Blood donation",
    category: "Health",
    proxy: "Cost per additional unit of blood collected (UK Health Security Agency)",
    proxyYear: "",
    unit: "donation",
    unitLabel: "donations",
    friendlyQuestion: "How many times do you donate blood each year?",
    defaultQuantity: 3,
    valuePerUnit: 130.0,
    sdg: "Good Health and Well-Being",
    sdgColor: "#4C9F38",
    description: "Regularly donating blood to help save lives and support the NHS.",
  },
  {
    id: "mental_health_support",
    name: "Supporting mental health as a volunteer",
    shortName: "Mental health support",
    category: "Health",
    proxy: "Average unit cost to the NHS of treating someone with depression (2024)",
    proxyYear: "2024",
    unit: "person",
    unitLabel: "people",
    friendlyQuestion: "How many people do you support with their mental health?",
    defaultQuantity: 2,
    valuePerUnit: 2856.0,
    sdg: "Good Health and Well-Being",
    sdgColor: "#4C9F38",
    description: "Volunteering with mental health organisations, crisis lines or peer support groups.",
  },
  {
    id: "sports_coaching",
    name: "Coaching or organising community sports",
    shortName: "Sports coaching",
    category: "Community",
    proxy: "Contribution of sport to wellbeing (2015)",
    proxyYear: "2015",
    unit: "participant",
    unitLabel: "people",
    friendlyQuestion: "How many people do you help get active through coaching or organising sport?",
    defaultQuantity: 10,
    valuePerUnit: 50.0,
    sdg: "Good Health and Well-Being",
    sdgColor: "#4C9F38",
    description: "Coaching, refereeing or organising community sports clubs and events.",
  },
  {
    id: "elderly_visiting",
    name: "Visiting elderly or isolated people",
    shortName: "Visiting isolated people",
    category: "Community",
    proxy: "Cost of loneliness (2015)",
    proxyYear: "2015",
    unit: "person",
    unitLabel: "people",
    friendlyQuestion: "How many people do you visit or check in on regularly?",
    defaultQuantity: 2,
    valuePerUnit: 763.0,
    sdg: "Good Health and Well-Being",
    sdgColor: "#4C9F38",
    description: "Regularly visiting elderly or isolated individuals to provide companionship.",
  },
  {
    id: "energy_saving",
    name: "Reducing home energy use",
    shortName: "Cutting home energy use",
    category: "Environment",
    proxy: "Energy savings from having floor insulation (soft furnishings)",
    proxyYear: "",
    unit: "household",
    unitLabel: "Households",
    friendlyQuestion: "This counts for your household — just confirm you do this.",
    defaultQuantity: 1,
    valuePerUnit: 75.0,
    sdg: "Affordable and Clean Energy",
    sdgColor: "#FCC30B",
    description: "Reducing energy consumption at home through efficiency measures or renewable energy.",
  },
  {
    id: "charity_volunteering",
    name: "General volunteering for a charity",
    shortName: "Charity volunteering",
    category: "Community",
    proxy: "Number of voluntary hours donated to support VCSEs",
    proxyYear: "",
    unit: "hour",
    unitLabel: "hours",
    friendlyQuestion: "How many hours do you give to charity volunteering each year?",
    defaultQuantity: 40,
    valuePerUnit: 17.0,
    sdg: "Reduced Inequalities",
    sdgColor: "#DD1367",
    description: "Regular volunteering time for any registered charity or community organisation.",
  },
  {
    id: "wildlife_conservation",
    name: "Wildlife or nature conservation volunteering",
    shortName: "Wildlife conservation",
    category: "Environment",
    proxy: "Ref 4.13 – Voluntary time for green infrastructure/biodiversity/green-space upkeep",
    proxyYear: "",
    unit: "hour",
    unitLabel: "hours",
    friendlyQuestion: "How many hours do you give to conservation work each year?",
    defaultQuantity: 20,
    valuePerUnit: 14.43,
    sdg: "Life on Land",
    sdgColor: "#56C02B",
    description: "Wildlife surveys, habitat management, or nature reserve volunteering.",
  },
  {
    id: "disaster_relief",
    name: "Disaster relief or emergency volunteering",
    shortName: "Emergency volunteering",
    category: "Community",
    proxy: "Number of voluntary hours donated to support VCSEs",
    proxyYear: "",
    unit: "hour",
    unitLabel: "hours",
    friendlyQuestion: "How many hours do you give to emergency or disaster relief volunteering each year?",
    defaultQuantity: 20,
    valuePerUnit: 17.0,
    sdg: "Sustainable Cities and Communities",
    sdgColor: "#F99D26",
    description: "Volunteering to support emergency services or community resilience during crises.",
  },
  {
    id: "rspb_donation",
    name: "Supporting wildlife charities (RSPB/WWF etc.)",
    shortName: "Supporting wildlife charities",
    category: "Environment",
    proxy: "Wildlife Trusts Basic Membership Fee (2026)",
    proxyYear: "2026",
    unit: "membership_year",
    unitLabel: "years",
    friendlyQuestion: "How many years have you supported a wildlife charity like RSPB or WWF?",
    defaultQuantity: 1,
    valuePerUnit: 20.0,
    sdg: "Life on Land",
    sdgColor: "#56C02B",
    description: "Supporting wildlife or environmental charities through membership or donations.",
  },
  {
    id: "literacy_support",
    name: "Literacy or homework volunteering",
    shortName: "Literacy support",
    category: "Education",
    proxy: "Value to an individual of improving literacy skills",
    proxyYear: "",
    unit: "person",
    unitLabel: "people",
    friendlyQuestion: "How many people do you help with reading, writing, or homework each year?",
    defaultQuantity: 2,
    valuePerUnit: 1500.0,
    sdg: "Quality Education",
    sdgColor: "#C5192D",
    description: "Supporting reading, writing or homework in schools, libraries, or community groups.",
  },
  {
    id: "digital_coaching",
    name: "Digital skills coaching",
    shortName: "Digital skills coaching",
    category: "Education",
    proxy: "Improved Digital Skills",
    proxyYear: "",
    unit: "person",
    unitLabel: "people",
    friendlyQuestion: "How many people do you help get online or improve their digital skills each year?",
    defaultQuantity: 3,
    valuePerUnit: 700.0,
    sdg: "Reduced Inequalities",
    sdgColor: "#DD1367",
    description: "Teaching digital skills to people who are excluded — elderly residents, job seekers, or anyone offline.",
  },
  {
    id: "arts_volunteering",
    name: "Community arts or creative volunteering",
    shortName: "Arts & creative groups",
    category: "Community",
    proxy: "Value of arts engagement (weekly active participation)",
    proxyYear: "",
    unit: "person",
    unitLabel: "people",
    friendlyQuestion: "How many people do you help engage with arts, music, drama, or creative activities?",
    defaultQuantity: 5,
    valuePerUnit: 448.0,
    sdg: "Good Health and Well-Being",
    sdgColor: "#4C9F38",
    description: "Volunteering with community arts, theatre, music or creative groups.",
  },
  {
    id: "litter_picking",
    name: "Litter picking and community clean-ups",
    shortName: "Litter picking",
    category: "Environment",
    proxy: "GMCA Welfare cost from significant litter accumulation in residential areas (high value) (2024)",
    proxyYear: "2024",
    unit: "session",
    unitLabel: "sessions",
    friendlyQuestion: "How many litter picking or community clean-up sessions do you take part in each year?",
    defaultQuantity: 6,
    valuePerUnit: 78.0,
    sdg: "Sustainable Cities and Communities",
    sdgColor: "#F99D26",
    description: "Picking up litter in parks, streets, beaches, or waterways to keep communities clean.",
  },
  {
    id: "employability_coaching",
    name: "Career and employability coaching",
    shortName: "Employability coaching",
    category: "Education",
    proxy: "Value of supporting young people into work (2024)",
    proxyYear: "2024",
    unit: "hour",
    unitLabel: "hours",
    friendlyQuestion: "How many hours of career coaching, CV help, or interview prep do you give each year?",
    defaultQuantity: 10,
    valuePerUnit: 133.0,
    sdg: "Decent Work and Economic Growth",
    sdgColor: "#A21942",
    description: "Helping young people with CVs, interview skills, work experience, and career planning.",
  },
  {
    id: "coding_education_child",
    name: "Teaching coding to children",
    shortName: "Teaching coding to children",
    category: "Education",
    proxy: "Cost of early childhood enrichment comparable to coding education (IFS, 2025)",
    proxyYear: "2025",
    unit: "child",
    unitLabel: "children",
    friendlyQuestion: "How many children do you teach coding to each year?",
    defaultQuantity: 5,
    valuePerUnit: 5000.0,
    sdg: "Quality Education",
    sdgColor: "#C5192D",
    description: "Teaching children to code, supporting digital literacy and future career prospects.",
  },
  {
    id: "coding_camp_week",
    name: "Running a coding or STEM camp",
    shortName: "Coding or STEM camp",
    category: "Education",
    proxy: "STEM/Coding Summer Camp Weekly Fee per child (Great British Summer Camp, 2024)",
    proxyYear: "2024",
    unit: "child_week",
    unitLabel: "child-weeks",
    friendlyQuestion: "How many child-weeks of coding or STEM camp do you run or volunteer at each year?",
    defaultQuantity: 10,
    valuePerUnit: 135.0,
    sdg: "Quality Education",
    sdgColor: "#C5192D",
    description: "Running or volunteering at coding or STEM camps for children.",
  },
  {
    id: "stem_workshop",
    name: "Delivering a STEM coding workshop",
    shortName: "STEM coding workshop",
    category: "Education",
    proxy: "Typical UK Full-Day STEM Workshop Cost (Hyett Education, 2025–26)",
    proxyYear: "2025",
    unit: "workshop",
    unitLabel: "workshops",
    friendlyQuestion: "How many full-day STEM or coding workshops do you deliver each year?",
    defaultQuantity: 3,
    valuePerUnit: 700.0,
    sdg: "Quality Education",
    sdgColor: "#C5192D",
    description: "Delivering full-day STEM or coding workshops to inspire and educate young people.",
  },
  {
    id: "family_caring",
    name: "Caring for a family member or someone in need",
    shortName: "Caring for family",
    category: "Health",
    proxy: "PSSRU Informal Carer Support — unit cost of unpaid care per person supported per year (Carers UK / PSSRU, 2022)",
    proxyYear: "2022",
    unit: "person",
    unitLabel: "people",
    friendlyQuestion: "How many family members or people do you provide regular unpaid care for?",
    defaultQuantity: 1,
    valuePerUnit: 7680.0,
    sdg: "Good Health and Well-Being",
    sdgColor: "#4C9F38",
    description: "Providing regular unpaid care, personal support, or assistance to a family member, friend, or neighbour who needs help due to illness, disability, or age.",
  },
  {
    id: "helping_neighbours",
    name: "Helping neighbours and informal community support",
    shortName: "Helping neighbours",
    category: "Community",
    proxy: "Cost of loneliness (2015)",
    proxyYear: "2015",
    unit: "person",
    unitLabel: "people helped",
    friendlyQuestion: "How many neighbours or community members do you help on a regular basis?",
    defaultQuantity: 2,
    valuePerUnit: 763.0,
    sdg: "Good Health and Well-Being",
    sdgColor: "#4C9F38",
    description: "Informal help for neighbours — shopping, errands, companionship, odd jobs, or just checking in on someone regularly.",
  },
  {
    id: "befriending",
    name: "Befriending or informal companionship support",
    shortName: "Befriending someone",
    category: "Community",
    proxy: "Cost of loneliness (2015)",
    proxyYear: "2015",
    unit: "person",
    unitLabel: "people",
    friendlyQuestion: "How many people do you provide regular companionship or befriending support to?",
    defaultQuantity: 1,
    valuePerUnit: 763.0,
    sdg: "Good Health and Well-Being",
    sdgColor: "#4C9F38",
    description: "Providing regular informal companionship, phone calls, or social support to reduce someone's isolation.",
  },
  {
    id: "dofe_bronze",
    name: "Duke of Edinburgh's Award — Bronze",
    shortName: "DofE Bronze Award",
    category: "Education",
    proxy: "Number of voluntary hours donated to support VCSEs",
    proxyYear: "",
    unit: "hour",
    unitLabel: "volunteering hours logged",
    friendlyQuestion: "How many volunteering hours did you log as part of your DofE Bronze Award?",
    defaultQuantity: 13,
    valuePerUnit: 17.0,
    sdg: "Quality Education",
    sdgColor: "#C5192D",
    description: "Volunteering, physical activity, and skill development as part of the Duke of Edinburgh's Bronze Award programme.",
  },
  {
    id: "dofe_silver",
    name: "Duke of Edinburgh's Award — Silver",
    shortName: "DofE Silver Award",
    category: "Education",
    proxy: "Number of voluntary hours donated to support VCSEs",
    proxyYear: "",
    unit: "hour",
    unitLabel: "volunteering hours logged",
    friendlyQuestion: "How many volunteering hours did you log as part of your DofE Silver Award?",
    defaultQuantity: 26,
    valuePerUnit: 17.0,
    sdg: "Quality Education",
    sdgColor: "#C5192D",
    description: "Volunteering, physical activity, and skill development as part of the Duke of Edinburgh's Silver Award programme.",
  },
  {
    id: "dofe_gold",
    name: "Duke of Edinburgh's Award — Gold",
    shortName: "DofE Gold Award",
    category: "Education",
    proxy: "Number of voluntary hours donated to support VCSEs",
    proxyYear: "",
    unit: "hour",
    unitLabel: "volunteering hours logged",
    friendlyQuestion: "How many volunteering hours did you log as part of your DofE Gold Award?",
    defaultQuantity: 52,
    valuePerUnit: 17.0,
    sdg: "Quality Education",
    sdgColor: "#C5192D",
    description: "Volunteering, physical activity, and skill development as part of the Duke of Edinburgh's Gold Award programme.",
  },
  {
    id: "school_fundraising",
    name: "School or community fundraising",
    shortName: "School fundraising",
    category: "Community",
    proxy: "Improved reputation of organisation/charity (2016)",
    proxyYear: "2016",
    unit: "event",
    unitLabel: "events",
    friendlyQuestion: "How many school or community fundraising events have you organised or taken part in?",
    defaultQuantity: 3,
    valuePerUnit: 185.0,
    sdg: "Reduced Inequalities",
    sdgColor: "#DD1367",
    description: "Organising or participating in school charity days, sponsored events, or community fundraising drives.",
  },
  {
    id: "job_club",
    name: "Job club or employment support participation",
    shortName: "Job club / employment group",
    category: "Community",
    proxy: "Value of supporting young people into work (2024)",
    proxyYear: "2024",
    unit: "hour",
    unitLabel: "hours",
    friendlyQuestion: "How many hours do you spend at a job club, employment support group, or skills workshop each year?",
    defaultQuantity: 30,
    valuePerUnit: 133.0,
    sdg: "Decent Work and Economic Growth",
    sdgColor: "#A21942",
    description: "Attending a job club, volunteering-to-work programme, or employment skills group to build skills and connections while helping others in the same boat.",
  },
  // ── Military / Forces service activities ──────────────────────────────────
  {
    id: "military_community_reconstruction",
    name: "Community reconstruction and development support",
    shortName: "Community reconstruction",
    category: "Community",
    proxy: "Number of voluntary hours donated to support VCSEs",
    proxyYear: "",
    unit: "hour",
    unitLabel: "hours",
    friendlyQuestion: "How many hours did you spend on community reconstruction or development work?",
    defaultQuantity: 200,
    valuePerUnit: 17.0,
    sdg: "Sustainable Cities and Communities",
    sdgColor: "#F99D26",
    description: "Supporting rebuilding and development of local communities — includes infrastructure support, local services, and civic projects delivered in operational or post-conflict environments.",
  },
  {
    id: "military_population_liaison",
    name: "Population liaison and cross-cultural community engagement",
    shortName: "Population liaison / CIMIC",
    category: "Community",
    proxy: "Number of voluntary hours donated to support VCSEs",
    proxyYear: "",
    unit: "hour",
    unitLabel: "hours",
    friendlyQuestion: "How many hours did you spend on community liaison or cross-cultural engagement work?",
    defaultQuantity: 100,
    valuePerUnit: 17.0,
    sdg: "Peace, Justice and Strong Institutions",
    sdgColor: "#00689D",
    description: "Building relationships with local communities, acting as a bridge between organisations and the public, and supporting cross-cultural communication and understanding.",
  },
  {
    id: "military_personnel_training",
    name: "Training and mentoring other personnel",
    shortName: "Training and mentoring personnel",
    category: "Education",
    proxy: "Adult learning course enabling someone to progress in work or in a career (2012)",
    proxyYear: "2012",
    unit: "person",
    unitLabel: "people trained",
    friendlyQuestion: "How many people have you trained, instructed, or mentored through your role?",
    defaultQuantity: 8,
    valuePerUnit: 75.0,
    sdg: "Quality Education",
    sdgColor: "#C5192D",
    description: "Delivering training, instruction, and mentoring to colleagues, junior personnel, or members of the public — including operational skills, safety training, and professional development.",
  },
  {
    id: "military_first_aid",
    name: "Emergency first aid delivery",
    shortName: "Emergency first aid",
    category: "Health",
    proxy: "Ambulance journey to hospital & A&E Attendance (2012)",
    proxyYear: "2012",
    unit: "person",
    unitLabel: "people helped",
    friendlyQuestion: "How many people have you provided emergency first aid to?",
    defaultQuantity: 5,
    valuePerUnit: 406.0,
    sdg: "Good Health and Well-Being",
    sdgColor: "#4C9F38",
    description: "Providing emergency first aid, medical triage, or health support in field, operational, or community settings.",
  },
  {
    id: "military_logistics",
    name: "Logistics and operational coordination",
    shortName: "Logistics coordination",
    category: "Community",
    proxy: "Number of voluntary hours donated to support VCSEs",
    proxyYear: "",
    unit: "hour",
    unitLabel: "hours",
    friendlyQuestion: "How many hours did you spend on logistics planning and coordination?",
    defaultQuantity: 150,
    valuePerUnit: 17.0,
    sdg: "Decent Work and Economic Growth",
    sdgColor: "#A21942",
    description: "Planning, coordinating, and managing logistics, supplies, and operational resources to support teams and community projects.",
  },
  // ── Career break / Returning to work activities ───────────────────────────
  {
    id: "career_break_childcare",
    name: "Full-time childcare coordination and parenting",
    shortName: "Childcare coordination",
    category: "Health",
    proxy: "PSSRU Informal Carer Support — unit cost of unpaid care per person supported per year (Carers UK / PSSRU, 2022)",
    proxyYear: "2022",
    unit: "person",
    unitLabel: "children",
    friendlyQuestion: "How many children did you provide full-time care and coordination for?",
    defaultQuantity: 1,
    valuePerUnit: 7680.0,
    sdg: "Good Health and Well-Being",
    sdgColor: "#4C9F38",
    description: "Full-time unpaid care, coordination, and advocacy for children — managing education, health appointments, and wellbeing during a career break.",
  },
  {
    id: "career_break_eldercare",
    name: "Eldercare management and coordination",
    shortName: "Eldercare management",
    category: "Health",
    proxy: "PSSRU Informal Carer Support — unit cost of unpaid care per person supported per year (Carers UK / PSSRU, 2022)",
    proxyYear: "2022",
    unit: "person",
    unitLabel: "people",
    friendlyQuestion: "How many elderly or dependent adults did you manage care for?",
    defaultQuantity: 1,
    valuePerUnit: 7680.0,
    sdg: "Good Health and Well-Being",
    sdgColor: "#4C9F38",
    description: "Managing care, health appointments, finances, and advocacy for elderly or dependent family members — coordinating across health, social care, and community services.",
  },
  {
    id: "career_break_school_liaison",
    name: "School liaison and education coordination",
    shortName: "School liaison",
    category: "Education",
    proxy: "Additional support through the common funding formula to help looked-after child achieve in school, per child per year (2017)",
    proxyYear: "2017",
    unit: "child",
    unitLabel: "children",
    friendlyQuestion: "How many children did you manage school liaison and education support for?",
    defaultQuantity: 1,
    valuePerUnit: 1187.0,
    sdg: "Quality Education",
    sdgColor: "#C5192D",
    description: "Acting as primary liaison with schools, teachers, and education authorities on behalf of children — including SEN support, parent engagement, and academic coordination.",
  },
  {
    id: "career_break_medical_coordination",
    name: "Medical appointment and healthcare management",
    shortName: "Medical appointment management",
    category: "Health",
    proxy: "Ambulance journey to hospital & A&E Attendance (2012)",
    proxyYear: "2012",
    unit: "appointment",
    unitLabel: "appointments managed",
    friendlyQuestion: "How many medical appointments did you coordinate and manage on behalf of dependants?",
    defaultQuantity: 20,
    valuePerUnit: 406.0,
    sdg: "Good Health and Well-Being",
    sdgColor: "#4C9F38",
    description: "Coordinating, managing, and attending medical appointments, specialist referrals, and healthcare decisions for dependants.",
  },
];

export const CATEGORIES = [...new Set(ACTIVITIES.map((a) => a.category))].sort();

interface CustomActivityInput {
  activityId: string;
  name: string;
  quantity: number;
  hoursPerYear: number;
  valuePerUnit: number;
  unit: string;
  proxy: string;
  proxyYear: string;
  sdg: string;
  sdgColor: string;
}

export function calculateImpact(
  activities: Array<{ activityId: string; quantity: number; hoursPerYear: number }>,
  donationsGBP: number,
  additionalVolunteerHours: number,
  customActivities: CustomActivityInput[] = []
) {
  // Clamp numeric inputs: treat NaN/negative as zero to prevent corrupted totals
  const safeDonations = Math.max(0, isNaN(donationsGBP) ? 0 : donationsGBP);
  const safeExtraHours = Math.max(0, isNaN(additionalVolunteerHours) ? 0 : additionalVolunteerHours);

  const VOLUNTEER_RATE = 12.21;   // National Living Wage 2024/25 — GOV.UK
  const PERSONAL_DEV_RATE_PER_HOUR = 15; // £15/hr — employer-valued skills premium, NCVO Time Well Spent 2023

  const activityBreakdowns = activities
    .map((sel) => {
      const activity = ACTIVITIES.find((a) => a.id === sel.activityId);
      if (!activity) return null;

      let impactValue = 0;
      if (activity.unit === "hour") {
        impactValue = sel.hoursPerYear * activity.valuePerUnit;
      } else {
        impactValue = sel.quantity * activity.valuePerUnit;
      }

      return {
        activityId: activity.id,
        activityName: activity.name,
        category: activity.category,
        proxy: activity.proxy,
        proxyYear: activity.proxyYear,
        sdg: activity.sdg,
        sdgColor: activity.sdgColor,
        impactValue: Math.round(impactValue * 100) / 100,
        hours: sel.hoursPerYear,
      };
    })
    .filter(Boolean) as Array<{
    activityId: string;
    activityName: string;
    category: string;
    proxy: string;
    proxyYear: string;
    sdg: string;
    sdgColor: string;
    impactValue: number;
    hours: number;
  }>;

  // Process custom activities (user-typed, with SVE proxy matched by AI)
  for (const ca of customActivities) {
    const impactValue =
      ca.unit === "hour"
        ? ca.hoursPerYear * ca.valuePerUnit
        : ca.quantity * ca.valuePerUnit;
    activityBreakdowns.push({
      activityId: ca.activityId,
      activityName: ca.name,
      category: "Custom",
      proxy: ca.proxy,
      proxyYear: ca.proxyYear,
      sdg: ca.sdg || "Good Health and Well-Being",
      sdgColor: ca.sdgColor || "#4C9F38",
      impactValue: Math.round(impactValue * 100) / 100,
      hours: ca.hoursPerYear,
    });
  }

  const totalActivityHours =
    activities.reduce((sum, a) => sum + a.hoursPerYear, 0) +
    customActivities.reduce((sum, a) => sum + a.hoursPerYear, 0);
  const totalHours = totalActivityHours + safeExtraHours;

  const impactValue = activityBreakdowns.reduce((sum, a) => sum + a.impactValue, 0);
  const contributionValue = totalHours * VOLUNTEER_RATE;
  const donationsValue = safeDonations;
  const personalDevelopmentValue = totalHours * PERSONAL_DEV_RATE_PER_HOUR;
  const totalValue = impactValue + contributionValue + donationsValue + personalDevelopmentValue;

  const sdgMap = new Map<string, { sdg: string; sdgColor: string; value: number }>();
  for (const b of activityBreakdowns) {
    if (!sdgMap.has(b.sdg)) {
      sdgMap.set(b.sdg, { sdg: b.sdg, sdgColor: b.sdgColor, value: 0 });
    }
    sdgMap.get(b.sdg)!.value += b.impactValue;
  }
  const sdgBreakdowns = Array.from(sdgMap.values()).map((s) => ({
    ...s,
    value: Math.round(s.value * 100) / 100,
  }));

  return {
    totalValue: Math.round(totalValue * 100) / 100,
    impactValue: Math.round(impactValue * 100) / 100,
    contributionValue: Math.round(contributionValue * 100) / 100,
    donationsValue: Math.round(donationsValue * 100) / 100,
    personalDevelopmentValue: Math.round(personalDevelopmentValue * 100) / 100,
    totalHours,
    activityBreakdowns,
    sdgBreakdowns,
    explanations: {
      impact:
        "This is the direct social value created by your activities — calculated using Social Value Engine proxy values based on academic research and government data. Each activity is matched to a recognised outcome and multiplied by how much you did.",
      contribution:
        "This is the value of your time. Every hour you volunteer is worth the National Living Wage (£12.21/hr). This recognises that your time has real economic value when given freely to others.",
      donations:
        "The direct monetary value of the money you've donated to good causes over the last year. Every pound donated creates real change for charities and communities.",
      personalDevelopment:
        "Volunteering doesn't just help others — it builds your skills too. This reflects the employer-valued skills premium from your volunteering hours, based on NCVO's Time Well Spent research (2023), which found employers value volunteering experience at an average £1,500/year — equivalent to £15 per hour.",
    },
  };
}
