CREATE TABLE IF NOT EXISTS public_profiles (
  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  slug TEXT UNIQUE NOT NULL,
  is_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  custom_message TEXT,
  show_hours BOOLEAN NOT NULL DEFAULT TRUE,
  show_sroi BOOLEAN NOT NULL DEFAULT TRUE,
  show_categories BOOLEAN NOT NULL DEFAULT TRUE,
  show_journal_highlights BOOLEAN NOT NULL DEFAULT FALSE,
  slug_customised BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
